# Generated by Django 5.0 on 2024-01-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0007_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_app.session_year'),
        ),
    ]
