# Generated by Django 4.1.5 on 2024-01-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0014_student_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_app.student'),
        ),
    ]
