# Generated by Django 4.1.5 on 2024-01-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0015_alter_student_feedback_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
