# Generated by Django 4.1.5 on 2024-01-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0021_student_result_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
