# Generated by Django 4.1.5 on 2024-01-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0022_student_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
    ]
