# Generated by Django 4.1.5 on 2024-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0023_remove_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
    ]
