# Generated by Django 4.1.5 on 2024-02-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0024_staff_feedback_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
    ]
