# Generated by Django 4.1.5 on 2024-02-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0025_student_feedback_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback',
            name='attachment',
        ),
    ]
